# Target Trial Emulation using observational data {#target-trial-emulation}

## Background

In 2016, Hernán and Rubins presented a framework to emulate a clinical trial using observational data when no clinical trial exists [@hernan_using_2016].The latter is a 2-step process: (1) **Specifying the target trial** (i.e., which is the hypothetical trial that could have been performed to answer the research question). This includes these elements eligibility criteria, treatment strategies, assignment procedures, follow-up period, outcome, causal contrast of interest and analysis plan, and (2) **Emulating each element** from the target trial.

Let us illustrate the TTE framework using our motivating example.

## Specify the target trial

As suggested, we specified the target trial as below:

+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Protocol component               | Target trial emulation                                                                                                                                                                                                                                                            |
+==================================+===================================================================================================================================================================================================================================================================================+
| **Eligibility criteria**         | Individuals aged 18 or older, newly diagnosed with PDD.                                                                                                                                                                                                                           |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Treatment strategies**         | Individuals who initiated Sertralex or Duloxyn.                                                                                                                                                                                                                                   |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Assignment procedures**        | Individuals randomly assigned to either strategy at baseline and are not aware of the assigned strategy (i.e., blinding)                                                                                                                                                          |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Follow-up period**             | Starts at randomization and ends at the first occurrence of a relapse event, loss to follow-up, or after one year of follow-up, whichever occurs first.                                                                                                                           |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Outcome**                      | Relapse (defined as a recurrence of depressive disorder) diagnosed by a clinician, identified through clinical assessment or documented diagnosis of depression during the follow-up period.                                                                                      |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Causal contrasts of interest** | Intention-to-treat (ITT)                                                                                                                                                                                                                                                          |
|                                  |                                                                                                                                                                                                                                                                                   |
|                                  | Per Protocol (PP)                                                                                                                                                                                                                                                                 |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Analysis plan**                | In both analyses (ITT and PP), Kaplan-Meier estimates and Cox proportional hazards models were utilized to compare the time to relapse from randomization between Sertralex and Duloxyn.                                                                                          |
|                                  |                                                                                                                                                                                                                                                                                   |
|                                  | In the PP analysis, individuals were censored at the time they switched from their initially assigned treatment to the alternative therapy. Additionally, inverse probability weighting was applied to adjust for post-baseline prognostic factors that may influence the switch. |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Emulate the target trial

Next, we examined each component and detailed how they can be derived using RWD.

**Eligibility criteria**: We included individuals aged 18 or older who were diagnosed with PDD, so no additional adjustments were necessary.

**Treatment strategies**: We defined two treatment strategies: either Sertralex or Duloxyn as the first prescription following a PDD diagnosis.

**Assignment procedures**: We assumed these two groups were exchangeable at index date conditionally on baseline covariates: Age at index date, gender, Beck score and socioeconomic status.

**Follow-up periods**: We defined time zero as the date of PDD diagnosis. From this point, we followed-up individuals until the earliest of the following events: first clinical relapse, loss of follow-up, 365 days after time zero, or time of treatment switch (for PP analysis only). 

**Outcomes**: We assumed the outcome as the first relapse occurring after time zero.

**Causal contrast of interest**: We considered observational analogues of the ITT and PP effect.

**Analysis plan**: For the ITT analysis, we used inverse probability weights (see chapter \@ref(iptw-application) for further details) to emulate the randomization process and applied these weights in the outcome analysis, including weighted Kaplan-Meier estimates and Cox proportional hazards models. For the PP analysis, we implemented the Clone-Censor-Weight method (see chapter for further details) for further detailto address both confounding and immortal time bias introduced by accounting for treatment switching in the analysis.